version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    user: '0:0'
    container_name: sqlserverappbuscar
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: PasswordO1.
      MSSQL_PID: Express
    volumes:
      - ~/docker/sqlserver-data:/var/opt/mssql
  #MySQL
  db:
    image: mysql:8
    container_name: db_appbuscar
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_appbuscar
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - appbuscar-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - appbuscar-network
    depends_on:
      - db

#Redes
networks:
  appbuscar-network:
    driver: bridge
#Volumenes
volumes:
  db_appbuscar:
    driver: local
